# Generated by Django 3.2.9 on 2022-01-15 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('special_offer', models.BooleanField(default=False, verbose_name='Special Offer?')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('availability', models.BooleanField(default=True)),
                ('MOQ', models.SmallIntegerField(blank=True, null=True, verbose_name='Minimum Order Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/product/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/product/images')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category')),
            ],
        ),
    ]
