# Generated by Django 3.2 on 2022-06-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='MOQ',
        ),
    ]
